{{- if and (not .Values.serviceEnv.existingSecret) .Values.serviceEnv.bootstrapContents }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hkclaw.serviceEnvSecretName" . }}
  labels:
    {{- include "hkclaw.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.serviceEnv.secretKey }}: |
{{ .Values.serviceEnv.bootstrapContents | indent 4 }}
{{- end }}
